# Generated by Django 4.1.1 on 2022-09-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_product_series_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_series',
            options={'verbose_name_plural': 'series'},
        ),
        migrations.AlterField(
            model_name='product_series',
            name='photo',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('series_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.product_series', verbose_name='series')),
            ],
        ),
    ]
