# Generated by Django 4.1.1 on 2022-09-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_product_series_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_series',
            name='url',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
