# Generated by Django 4.1.1 on 2022-09-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_product_series_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
